version: '3.8'

services:
  backend:
    image: todo-app:backend
    ports:
      - "4000:8080"
      - "9400:9400"
      
      
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
